development:
  adapter: postgresql
  encoding: unicode
  database: korning_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: korning_test
  pool: 5
  username:
  password:
